title: 4k29
description: AppleとNothing、UI、デザイン、写真について学生目線で考える個人サイト。
url: https://4k29.github.io
baseurl: /4k29
lang: ja
timezone: Asia/Tokyo
encoding: utf-8

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

collections:
  memories:
    output: true
    permalink: /memory/:name.html
    sort_by: date
  notes:
    output: true
    permalink: /notes/:name.html
    sort_by: date
    future: true

defaults:
  - scope:
      path: ""
      type: memories
    values:
      layout: memory
  - scope:
      path: ""
      type: notes
    values:
      layout: note
      author: うまいしか

exclude:
  - node_modules
  - package.json
  - package-lock.json
  - vendor
