import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {Conversation} from '../docs/dialogue.js';
const data=JSON.parse(fs.readFileSync(new URL('../docs/profile.json',import.meta.url)));
for(const [q,id] of [['AIの未来の記事が読みたい','note-ai-future'],['SLMについての記事','note-ai-future'],['非生成コンテンツの記事を読みたい','note-ai-and-experience'],['Sam Kolderの記事ある？','note-ai-and-experience'],['iPhone Duoの記事を読みたい','note-iphone-duo-os'],['折りたたみについての記事','note-iphone-duo-os'],['Apple Watchの記事が読みたい','note-applewatch-siriai'],['Siriの記事は？','note-applewatch-siriai'],['Nothingの記事読みたい','note-nothing-headphone-1'],['ヘッドホンのレビュー記事','note-nothing-headphone-1'],['Instagramの記事を見たい','note-instants'],['SNSの記事','note-instants'],['iPhone eの記事','note-iphone-e']])test(q,()=>{const a=new Conversation(data).respond(q);assert.deepEqual(a.factIds,[id]);assert.equal(a.links[0].url,data.facts.find(f=>f.id===id).url);assert.match(a.text,/読めます/);});
test('broad themes offer all matching articles without an arbitrary selection',()=>{for(const q of ['AIの記事を読みたい','iPhoneの記事は？']){const a=new Conversation(data).respond(q);assert.ok(a.links.length>1);assert.equal(a.links.length,a.factIds.length);assert.equal(a.text.split('\n').length,a.links.length);}});
test('no theme returns Notes and unmatched themes do not invent article links',()=>{for(const q of ['記事を読みたい','宇宙旅行の記事を読みたい'])assert.equal(new Conversation(data).respond(q).links[0].url,'https://4k29.github.io/tecirc/notes/');assert.deepEqual(new Conversation(data).respond('どんなヘッドホンを使ってる？').factIds,['headphones']);});

for(const q of ['ランニングは何使ってるの','らんにんぐはなにつかってるの','ランニングの道具は？','ランニングで使うギアは？','What gear do you use for running?'])test('running gear: '+q,()=>{const a=new Conversation(data).respond(q);assert.deepEqual(a.factIds,['running-shoes']);assert.match(a.text,/NIKE PEGASUS TRAIL 5 GORE‑TEX/);assert.doesNotMatch(a.text,/取り組んでいます/);});
for(const q of ['ランニングで使う時計は何を使ってる？','ランニングのアプリは何使う？'])test('unknown running gear: '+q,()=>assert.equal(new Conversation(data).respond(q).text,data.unknownReply));

test('equipment follow-up uses a single running antecedent without training it as standalone',()=>{const c=new Conversation(data);c.respond('ランニングしてる？');const a=c.respond('何使ってる？');assert.deepEqual(a.factIds,['running-shoes']);assert.equal(a.learningEligible,false);});
