const {chromium}=require('playwright');const assert=require('node:assert/strict');const fs=require('node:fs');
const base=process.env.SITE_URL||'http://localhost:8001/';
(async()=>{const browser=await chromium.launch({headless:true,...(process.env.BROWSER_EXECUTABLE?{executablePath:process.env.BROWSER_EXECUTABLE}:{}),...(process.env.USE_PROXY?{proxy:{server:process.env.HTTPS_PROXY}}:{})});
for(const mobile of [false,true])for(const scheme of ['dark','light']){
 const ctx=await browser.newContext({viewport:mobile?{width:390,height:844}:{width:1440,height:900},colorScheme:scheme,reducedMotion:'reduce'});await ctx.addInitScript(()=>{localStorage.setItem('4k29.theme','light');});const p=await ctx.newPage(),errors=[],remote=[];p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(!r.url().startsWith(base))remote.push(r.url());});
 await p.goto(base);await p.waitForFunction(()=>!document.querySelector('#prompt-form button').disabled);assert.equal(await p.locator('#transition,.chat-disclaimer').count(),0);assert.equal(await p.locator('html').getAttribute('data-theme'),scheme);assert.equal(await p.locator('#theme').innerText(),scheme==='dark'?'☀':'☾');assert.equal(await p.locator('#theme').getAttribute('aria-label'),scheme==='dark'?'ライトモードに切り替え':'ダークモードに切り替え');
 let n=0;async function ask(q){await p.locator('#prompt-input').fill(q);await p.locator('#prompt-input').press('Enter');n++;await p.waitForFunction(n=>document.querySelectorAll('.chat-response').length===n&&document.querySelector('#chat').getAttribute('aria-busy')==='false',n);return p.locator('.chat-response').nth(n-1);}
 let a=await ask('あなたの記事が読みたい');assert.equal(await a.getByRole('link',{name:'Tecirc',exact:true}).getAttribute('href'),'https://4k29.github.io/tecirc/');a=await ask('ランニングはどこ走ってるの？');assert.equal(await a.innerText(),'すみません、よく分かりません');a=await ask('趣味は？');assert.doesNotMatch(await a.innerText(),/Web|ウェブ/);assert.doesNotMatch(await p.locator('.events').innerText(),/websites/);
 await p.locator('#question-history > summary').click();assert.equal(await p.locator('.history-record').count(),3);await p.locator('.history-record').first().locator('summary').click();await p.locator('.history-record').first().getByRole('button',{name:'見直しに追加'}).click();assert.match(await p.locator('.history-record').first().locator('summary').innerText(),/見直し/);
 const downloadReady=p.waitForEvent('download');await p.locator('#history-export').click();const download=await downloadReady;assert.equal(download.suggestedFilename(),'4k29-question-history.json');const data=JSON.parse(fs.readFileSync(await download.path(),'utf8'));assert.equal(data.records.length,3);assert.equal(data.records[1].unanswered,true);assert.equal(data.records[2].needsReview,true);assert.ok(data.records.every(r=>r.engine&&r.session&&r.factIds));assert.equal(JSON.stringify(data).includes('userAgent'),false);
 const firstSession=data.records[0].session;await p.locator('#replay').click();await p.waitForFunction(()=>!document.querySelector('#prompt-form button').disabled);n=0;a=await ask('何のイヤホン使ってる');assert.match(await a.innerText(),/Beats Fit ProとCMF Buds/);const saved=await p.evaluate(()=>JSON.parse(localStorage.getItem('4k29.question-journal.v1')));assert.equal(saved.records.length,4);assert.equal(saved.records[3].learningEligible,true);assert.equal(saved.records[3].learned,false);assert.notEqual(saved.records[3].session,firstSession);
 await p.locator('#theme').click();const chosen=scheme==='dark'?'light':'dark';assert.equal(await p.locator('html').getAttribute('data-theme'),chosen);await p.emulateMedia({colorScheme:chosen});await p.emulateMedia({colorScheme:scheme});assert.equal(await p.locator('html').getAttribute('data-theme'),chosen);
 await p.reload();await p.waitForFunction(()=>!document.querySelector('#prompt-form button').disabled);assert.equal(await p.locator('html').getAttribute('data-theme'),scheme);assert.equal(await p.locator('.history-record').count(),4);assert.equal(await p.locator('.chat-turn').count(),0);n=0;
 await p.locator('#question-history > summary').click();await p.locator('#history-clear').click();assert.equal(await p.locator('.history-record').count(),0);assert.equal(await p.evaluate(()=>localStorage.getItem('4k29.question-journal.v1')),null);
 a=await ask('ランニングに使ってる靴は？');assert.match(await a.innerText(),/NIKE PEGASUS TRAIL 5 GORE‑TEX/);await ask('<img src=x onerror=alert(1)>');assert.equal(await p.locator('#question-history img').count(),0);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);assert.deepEqual(remote,[]);await p.screenshot({path:`/tmp/history-${mobile?'mobile':'desktop'}-${scheme}.png`,fullPage:true});console.log(`PASS ${mobile?'mobile':'desktop'} ${scheme}: correct articles/running, removed Web, local history/review/export/reload/clear, session provenance, binary system theme, no XSS/external requests`);await ctx.close();
}
await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
