const {chromium}=require('playwright');const assert=require('node:assert/strict');
const base=process.env.SITE_URL||'http://localhost:8001/';
(async()=>{const browser=await chromium.launch({headless:true,...(process.env.BROWSER_EXECUTABLE?{executablePath:process.env.BROWSER_EXECUTABLE}:{}),...(process.env.USE_PROXY?{proxy:{server:process.env.HTTPS_PROXY}}:{})});
for(const mobile of [false,true])for(const scheme of ['dark','light']){
 const ctx=await browser.newContext({viewport:mobile?{width:390,height:844}:{width:1440,height:900},colorScheme:scheme,reducedMotion:'reduce'}),p=await ctx.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(base);await p.waitForFunction(()=>!document.querySelector('#prompt-form button').disabled);
 assert.equal(await p.locator('#question-history,#history-export,#history-clear,.sim-label').count(),0);assert.equal(await p.locator('.header-controls #theme').count(),1);assert.equal(await p.locator('.header-controls .language-button').count(),2);assert.equal(await p.locator('html').getAttribute('data-theme'),scheme);await p.locator('#theme').click();assert.equal(await p.locator('html').getAttribute('data-theme'),scheme==='dark'?'light':'dark');
 const header=await p.locator('.header-controls').boundingBox(),device=await p.locator('.device-panel').boundingBox();assert.ok(header.y+header.height<=device.y);await p.locator('#prompt-input').fill('何のイヤホン使ってる？');await p.locator('#prompt-input').press('Enter');await p.waitForFunction(()=>document.querySelector('.chat-response')&&document.querySelector('#chat').getAttribute('aria-busy')==='false');assert.match(await p.locator('.chat-response').innerText(),/Beats Fit ProとCMF Buds/);
 const records=await p.evaluate(()=>JSON.parse(localStorage.getItem('4k29.question-journal.v1')).records);assert.equal(records.length,1);assert.equal(records[0].learningEligible,true);await p.reload();await p.waitForFunction(()=>!document.querySelector('#prompt-form button').disabled);assert.equal(await p.evaluate(()=>JSON.parse(localStorage.getItem('4k29.question-journal.v1')).records.length),1);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);await p.screenshot({path:`/tmp/header-${mobile?'mobile':'desktop'}-${scheme}.png`,fullPage:true});console.log(`PASS ${mobile?'mobile':'desktop'} ${scheme}: header controls, removed history tools, retained local learning, no overflow`);await ctx.close();
}await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
