const {chromium}=require('playwright');const assert=require('node:assert/strict');
const base=process.env.SITE_URL||'http://localhost:8001/';
const captureDir=process.env.CAPTURE_DIR||'/tmp/4k29-browser-tests';
require('node:fs').mkdirSync(captureDir,{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true,...(process.env.BROWSER_EXECUTABLE?{executablePath:process.env.BROWSER_EXECUTABLE}:{})});
for(const mobile of [false,true])for(const scheme of ['dark','light']){
 const ctx=await browser.newContext({viewport:mobile?{width:390,height:844}:{width:1440,height:900},isMobile:mobile,hasTouch:mobile,colorScheme:scheme,reducedMotion:'reduce'});const page=await ctx.newPage();const errors=[],remote=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!r.url().startsWith(base))remote.push(r.url())});
 await page.goto(base);await page.waitForFunction(()=>!document.querySelector('#boot-next').disabled);assert.match(await page.locator('#boot-log').innerText(),/OS:|Unknown/);
 if(mobile)await page.locator('#boot-next').click();else await page.keyboard.press('Enter');await page.waitForFunction(()=>document.querySelector('#profile:not(.stage-hidden)')&&!document.querySelector('#prompt-form button').disabled);
 assert.match(await page.locator('.reply').first().innerText(),/I'm しか/);assert.match(await page.locator('.events').innerText(),/Mostly AI-generated/);
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),mobile?390:1440);
 const input=page.locator('#prompt-input');await input.fill('名前は？');await input.dispatchEvent('keydown',{key:'Enter',isComposing:true,bubbles:true});assert.equal(await page.locator('.chat-turn').count(),0);if(mobile){await input.press('Enter');assert.equal(await page.locator('.chat-turn').count(),0);await input.fill('名前は？');}if(mobile)await page.locator('button[type=submit]').click();else await input.press('Enter');await page.waitForFunction(()=>document.querySelectorAll('.chat-response').length===1&&document.querySelector('#chat').getAttribute('aria-busy')==='false');assert.match(await page.locator('.chat-response').innerText(),/4k29/);
 await input.fill('デザイン');await input.press('Shift+Enter');assert.match(await input.inputValue(),/\n/);await page.locator('button[type=submit]').click();await page.waitForFunction(()=>document.querySelectorAll('.chat-response').length===2&&document.querySelector('#chat').getAttribute('aria-busy')==='false');
 await input.fill('もっと');await page.locator('button[type=submit]').click();await page.waitForFunction(()=>document.querySelectorAll('.chat-response').length===3&&document.querySelector('#chat').getAttribute('aria-busy')==='false');assert.match(await page.locator('.chat-response').nth(2).innerText(),/デザイン|余白/);
 await input.fill('<img src=x onerror=alert(1)>');await page.locator('button[type=submit]').click();await page.waitForFunction(()=>document.querySelectorAll('.chat-response').length===4&&document.querySelector('#chat').getAttribute('aria-busy')==='false');assert.equal(await page.locator('#chat img').count(),0);
 for(let n=4;n<20;n++){await input.fill('興味は？');await page.locator('button[type=submit]').click();await page.waitForFunction(n=>document.querySelectorAll('.chat-response').length===n&&document.querySelector('#chat').getAttribute('aria-busy')==='false',n+1);}
 await input.fill('hello');await page.locator('button[type=submit]').click();await page.waitForFunction(()=>!document.querySelector('#limit').classList.contains('stage-hidden'));assert.match(await page.locator('#limit').innerText(),/Usage limit reached/);assert.equal(await page.locator('.chat-response').count(),20);
 await page.locator('#replay').click();await page.waitForFunction(()=>!document.querySelector('#prompt-form button').disabled);assert.equal(await page.locator('.chat-turn').count(),0);
 await input.fill('愛用製品は？');await page.locator('button[type=submit]').click();await page.waitForFunction(()=>document.querySelector('#chat').getAttribute('aria-busy')==='false');assert.match(await page.locator('.chat-response').innerText(),/Nothing Headphone/);
 await page.screenshot({path:`${captureDir}/final-${mobile?'mobile':'desktop'}-${scheme}.png`,fullPage:true});
 await page.locator('#theme').click();assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');await page.locator('#theme').click();assert.equal(await page.locator('html').getAttribute('data-theme'),'light');
 await page.reload();await page.waitForFunction(()=>!document.querySelector('#prompt-form button').disabled);assert.equal(await page.locator('#boot').count(),0);assert.equal(await page.locator('#chat').innerText(),'');assert.deepEqual(errors,[]);assert.deepEqual(remote,[]);console.log(`PASS ${mobile?'mobile':'desktop'} ${scheme}: boot, intro, chat, multiline, follow-up, XSS, quota/replay, theme, reload, no external requests`);await ctx.close();
}
// Normal motion: observe boot, animated transition, thinking and incremental text.
const ctx=await browser.newContext({reducedMotion:'no-preference'});const page=await ctx.newPage();await page.goto(base);await page.waitForFunction(()=>!document.querySelector('#boot-next').disabled);await page.locator('#boot-next').click();await page.waitForSelector('#transition:not(.stage-hidden)');assert.equal(await page.locator('#transition .spinner i').count(),3);await page.waitForSelector('.thinking');await page.waitForFunction(()=>document.querySelector('.reply:not(.stage-hidden) p')?.textContent.length>0);const partial=await page.locator('.reply p').innerText();assert.ok(partial.length<130);console.log('PASS normal motion: boot/transition/thinking/incremental typing');await ctx.close();await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
