import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {Conversation} from '../docs/dialogue.js';import {intentExamples} from '../docs/intent-examples.js';import {composeAnswer} from '../docs/answer-composition.js';
const data=JSON.parse(fs.readFileSync(new URL('../docs/profile.json',import.meta.url)));
for(const intent of intentExamples)for(const q of intent.examples)test('audited question: '+q,()=>{const a=new Conversation(data).respond(q);assert.deepEqual(new Set(a.factIds),new Set(intent.facts));});
test('removed Web development is not advertised in profile or answered as an activity',()=>{assert.equal(data.facts.some(f=>f.id==='web'),false);for(const q of ['Web開発は何をしているの？','Web開発では何をしてる？','うぇぶかいはつはなにをしてるの','Web制作する？'])assert.equal(new Conversation(data).respond(q).text,data.unknownReply,q);assert.doesNotMatch(new Conversation(data).respond('趣味は？').text,/Web|ウェブ/);});
test('unregistered running location is not answered with a generic activity',()=>{for(const q of ['ランニングはどこ走ってるの？','どこでランニングしてる？','ランニングのコースは？','らんにんぐはどこはしってるの'])assert.equal(new Conversation(data).respond(q).text,data.unknownReply,q);});
test('brand facts are never described as academic fields in any wording variant',()=>{for(let variant=0;variant<4;variant++){const facts=data.facts.filter(f=>['apple','nothing'].includes(f.id));const a=composeAnswer(facts,[{unknown:false}],'ja',variant);assert.doesNotMatch(a,/関心のある分野/);assert.match(a,/AppleとNothing/);}});

test('running shoes use the supplied model without inventing location or specifications',()=>{for(const q of ['ランニングに使ってる靴は？','ランニングのシューズは何？','どんな靴履いてる？','らんにんぐのくつはなに']){const a=new Conversation(data).respond(q);assert.deepEqual(a.factIds,['running-shoes']);assert.match(a.text,/NIKE PEGASUS TRAIL 5 GORE‑TEX/);}for(const q of ['ランニングの靴は何色？','ランニングの靴はいくら？','ランニングはどこ走ってる？'])assert.equal(new Conversation(data).respond(q).text,data.unknownReply,q);});

test('known and unknown parts receive scoped answers without a generic apology',()=>{for(const q of ['名前と年齢は？','名前は？年齢は？','なまえとねんれいは？']){const a=new Conversation(data).respond(q);assert.match(a.text,/4k29（しか）/);assert.match(a.text,/年齢については、まだ答えられません/);assert.doesNotMatch(a.text,/すみません、よく分かりません/);assert.equal(a.unanswered,true);}const a=new Conversation(data).respond('名前と年齢と趣味は？');assert.match(a.text,/Tecirc/);assert.match(a.text,/年齢については、まだ/);assert.equal(new Conversation(data).respond('年齢は？').text,data.unknownReply);});
