import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {Conversation} from '../docs/dialogue.js';
const data=JSON.parse(fs.readFileSync(new URL('../docs/profile.json',import.meta.url)));
for(const q of ['What music do you like?','Which games do you enjoy?','What is my favorite person?','What is OpenAI?','What is Apple?'])test('English topic and subject guards: '+q,()=>assert.equal(new Conversation(data).respond(q).text,data.unknownReply));
test('English mixed known/unknown names the missing attribute without losing the answer',()=>{const a=new Conversation(data).respond('What is your name and how old are you?');assert.match(a.text,/4k29/);assert.match(a.text,/your age/);assert.doesNotMatch(a.text,/すみません/);assert.equal(a.unanswered,true);});
test('English contextual names use registered products and are not independent learning examples',()=>{const c=new Conversation(data);c.respond('What earbuds do you use?');const a=c.respond('What are they called?');assert.match(a.text,/Beats Fit Pro/);assert.match(a.text,/CMF Buds/);assert.equal(a.learningEligible,false);});
test('English favorite YouTube is distinct from the owner unregistered YouTube',()=>{const c=new Conversation(data);const a=c.respond('What is your favorite person’s YouTube channel?');assert.deepEqual(a.factIds,['favorite-person']);assert.equal(a.links.length,1);assert.equal(a.links[0].url,'https://m.youtube.com/@shiteharu?ra=m');assert.equal(c.respond('What is your YouTube channel?').text,data.unknownReply);});
test('English replies have varied phrasing and invariant facts',()=>{for(const q of ['What is your name?','Who is your favorite person?','What are your subscriptions?']){const c=new Conversation(data),answers=Array.from({length:5},()=>c.respond(q));assert.ok(new Set(answers.map(a=>a.text)).size>=4);for(const a of answers){assert.equal(a.language,'en');assert.deepEqual(new Set(a.factIds),new Set(answers[0].factIds));}}});

test('English favorite channel follow-up uses only the established person',()=>{const c=new Conversation(data);c.respond('Who is your favorite person?');const a=c.respond('What is their YouTube channel?');assert.equal(a.links[0].url,'https://m.youtube.com/@shiteharu?ra=m');assert.equal(a.links.length,1);assert.equal(a.learningEligible,false);});
