import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {Conversation} from '../docs/dialogue.js';
const data=JSON.parse(fs.readFileSync(new URL('../docs/profile.json',import.meta.url)));
for(const q of ['なんの記事書いてるの','何の記事を書いているの？','なんのきじかいてるの','記事は何書いてる？','ブログはどんな内容？'])test('article subject: '+q,()=>{const c=new Conversation(data);for(let n=0;n<4;n++){const a=c.respond(q);assert.ok(a.factIds.includes('tecirc-subjects'));assert.match(a.text,/テクノロジー、デザイン、製品の使い心地/);assert.ok(a.links.some(l=>l.url==='https://4k29.github.io/tecirc/notes/'));assert.ok(a.text.indexOf('テクノロジー')<a.text.indexOf('Tecirc'));assert.doesNotMatch(a.text,/取り組んで|記事執筆/);}});
for(const q of ['趣味は','しゅみは？','趣味について教えて','What are your hobbies?'])test('hobby subject: '+q,()=>{const c=new Conversation(data);for(let n=0;n<4;n++){const a=c.respond(q);assert.match(a.text,/趣味|\bhobb(?:y|ies)\b/i);assert.match(a.text,/写真|photographs/);assert.doesNotMatch(a.text,/Tecirc/);assert.doesNotMatch(a.text,/取り組んで|活動として|My activities/);}});
test('article location and unknown personal details retain distinct answers',()=>{const c=new Conversation(data);assert.deepEqual(c.respond('記事はどこで読める？').factIds,['tecirc-link']);assert.equal(c.respond('記事を書くのに何時間かかる？').text,data.unknownReply);});

for(const q of ['好きな人は？','好きな人物は誰？','すきなひとはだれ','好きなひと教えて'])test('favorite person equivalence: '+q,()=>{const a=new Conversation(data).respond(q);assert.deepEqual(a.factIds,['favorite-person']);assert.match(a.text,/(?:推し|好きな人).*してはる/);});

test('article reading links to Notes or a verified individual article',()=>{const c=new Conversation(data);const generic=c.respond('記事読みたい');assert.equal(generic.links[0].url,'https://4k29.github.io/tecirc/notes/');assert.match(generic.text,/Notes一覧/);const specific=c.respond('iPhone eシリーズの記事を読みたい');assert.equal(specific.links[0].url,'https://4k29.github.io/tecirc/notes/iPhone-e/');assert.match(specific.text,/iPhone eシリーズの意義を考える/);const unknown=c.respond('宇宙旅行の記事を読みたい');assert.equal(unknown.links[0].url,'https://4k29.github.io/tecirc/notes/');assert.equal(c.respond('iPhone eはいくら？').text,data.unknownReply);});

test('favorite person links are registered and can be requested by channel',()=>{const c=new Conversation(data);assert.deepEqual(c.respond('好きな人は？').links.map(l=>l.url),['https://m.youtube.com/@shiteharu?ra=m','https://x.com/popico_pi']);assert.deepEqual(c.respond('してはるのYouTube教えて').links.map(l=>l.url),['https://m.youtube.com/@shiteharu?ra=m']);assert.deepEqual(c.respond('してはるのTwitter教えて').links.map(l=>l.url),['https://x.com/popico_pi']);});
