import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {searchIntent,webLinks} from '../docs/search-intent.js';
import {SearchController} from '../docs/search-controller.js';
import {fetchJSON,findPlaces,getWeather,formatWeather,weatherCode,locate} from '../docs/search-services.js';
import {Conversation} from '../docs/dialogue.js';
const place={name:'東京都',latitude:35.68,longitude:139.69,country:'日本'};
const fixture={timezone:'Asia/Tokyo',current:{time:'2026-10-02T22:00',weather_code:1,temperature_2m:18.2},daily:{time:['2026-10-02','2026-10-03','2026-10-04'],weather_code:[61,3,0],temperature_2m_max:[22,23,24],temperature_2m_min:[17,18,19],precipitation_probability_max:[80,30,0]}};
for(const [q,name,day] of [['今日の天気は？','',0],['明日の東京の天気','東京',1],['とうきょうのてんきは','とうきょう',0],['大阪は明日雨が降る？','大阪',1],['東京の気温は何度','東京',0],['weather in Tokyo tomorrow','Tokyo',1]])test('weather intent: '+q,()=>{const p=searchIntent(q);assert.equal(p.kind,'weather');assert.equal(p.place,name);assert.equal(p.day,day);});
test('personal questions do not become external searches',()=>{for(const q of ['あなた誰？','契約してるサブスクは？','推しは誰？','あなたの好きな天気は？','私の名前は？','誕生日は？'])assert.equal(searchIntent(q),null,q);});
test('unknown questions are not automatically transmitted',()=>{assert.equal(searchIntent('宇宙とは？'),null);assert.equal(searchIntent('宇宙とは？',{forceSearch:true}).kind,'web');assert.equal(searchIntent('OpenAIを検索して').query,'OpenAI');});
test('latest information uses real search destinations without fabricated summaries',async()=>{const c=new SearchController();const a=await c.execute(c.plan('今日のニュースは？'));assert.match(a.text,/最新情報は検索先/);assert.equal(a.links.length,1);assert.equal(new URL(a.links[0].url).searchParams.get('q'),'今日のニュースは?');});
test('weather without region does not read location or contact a service',async()=>{const c=new SearchController({locate:()=>{throw Error('automatic location')},findPlaces:()=>{throw Error('automatic geocode')}});const a=await c.execute(c.plan('今日の天気は？'));assert.equal(a.actions[0].type,'geolocate');assert.equal(c.pendingWeather,true);assert.equal(c.plan('東京').place,'東京');});
test('profile question cancels pending region request',async()=>{const c=new SearchController();await c.execute(c.plan('今日の天気は？'));assert.equal(c.plan('イヤホンは？',{profileKnown:true}),null);assert.equal(c.pendingWeather,false);});
test('ambiguous place requires choosing a candidate',async()=>{let selected;const c=new SearchController({findPlaces:async()=>[place,{...place,name:'別の東京'}],getWeather:async p=>{selected=p;return {text:p.name}}});const a=await c.execute(c.plan('東京の天気'));assert.equal(a.actions.length,2);assert.equal(selected,undefined);await c.execute({kind:'weather'},a.actions[1]);assert.equal(selected.name,'別の東京');});
test('location is read only for explicit action and denied permissions recover',async()=>{let reads=0;const c=new SearchController({locate:async()=>{reads++;throw Error('denied')}});const a=await c.execute(c.plan('現在地の天気'));assert.equal(reads,0);const b=await c.execute({kind:'weather'},a.actions[0]);assert.equal(reads,1);assert.match(b.text,/地域名/);});
test('location action preserves requested day and rounds coordinates',async()=>{const p=await locate({getCurrentPosition:ok=>ok({coords:{latitude:35.6895123,longitude:139.6917123}})});assert.equal(p.latitude,35.69);assert.equal(p.longitude,139.69);let day;const c=new SearchController({locate:async()=>p,getWeather:async(_p,d)=>{day=d;return {text:'forecast'}}});const a=await c.execute(c.plan('明日の天気'));c.day=0;await c.execute({kind:'weather'},a.actions[0]);assert.equal(day,1);});
test('new unknown region never reuses previous location silently',async()=>{const c=new SearchController({findPlaces:async()=>[]});c.place=place;await c.execute(c.plan('存在しない地域の天気'));assert.equal(c.place,null);});
test('weather format preserves dates, missing values and model provenance',()=>{const a=formatWeather(fixture,place,1,new Date('2026-10-02T13:00:00Z'));assert.match(a.text,/明日（2026-10-03）/);assert.match(a.text,/最高 23°C/);assert.match(a.text,/30%/);assert.doesNotMatch(a.text,/現在の推定/);assert.match(a.text,/予報・モデル推定/);assert.match(formatWeather({...fixture,current:null,daily:{...fixture.daily,temperature_2m_max:[null]}},place,0).text,/最高 Unknown/);assert.equal(weatherCode(999),'Unknown');assert.throws(()=>formatWeather({daily:{}},place,0));});
test('unsupported forecast period uses search links without weather request',async()=>{const c=new SearchController({getWeather:()=>{throw Error('unsupported period')}});const a=await c.execute(c.plan('来週の東京の天気'));assert.match(a.text,/今日・明日・明後日/);assert.match(a.links[0].url,/来週|%E6/);});
test('network requests omit cookies and referrers, use finite timeout, and carry only requested data',async()=>{let seen;await fetchJSON('https://example.test/',{fetcher:async(url,init)=>{seen=init;return {ok:true,json:async()=>({})}}});assert.equal(seen.credentials,'omit');assert.equal(seen.referrerPolicy,'no-referrer');await assert.rejects(fetchJSON('https://example.test/',{timeout:5,fetcher:(_url,{signal})=>new Promise((_r,reject)=>signal.addEventListener('abort',()=>reject(Error('timeout'))))}),/timeout/);});
test('Japanese location spelling is translated without fabricated coordinates',async()=>{let query;const p=await findPlaces('とうきょう',{fetcher:async url=>{query=url;return {ok:true,json:async()=>({results:[{...place,country_code:'JP'},{...place,country_code:'US'}, {name:'bad',latitude:999,longitude:0}]})}}});assert.equal(new URL(query).searchParams.get('name'),'Tokyo');assert.equal(p.length,1);assert.equal(p[0].latitude,35.68);});
test('weather service uses only coordinates and declared forecast fields',async()=>{let query;await getWeather(place,0,{fetcher:async url=>{query=url;return {ok:true,json:async()=>fixture}}});assert.equal(new URL(query).hostname,'api.open-meteo.com');assert.equal(new URL(query).searchParams.get('latitude'),'35.68');assert.equal(new URL(query).searchParams.has('question'),false);await assert.rejects(getWeather({...place,latitude:999},0));});
test('Google search does not fetch or copy third-party results',async()=>{const c=new SearchController();const a=await c.execute(c.plan('OpenAIを検索して'));assert.match(a.text,/別タブ/);assert.equal(a.links.length,1);assert.equal(new URL(a.links[0].url).hostname,'www.google.com');});
test('failed weather request offers Google fallback',async()=>{const c=new SearchController({getWeather:async()=>{throw Error('offline')}});c.place=place;const a=await c.execute(c.plan('今日の天気'));assert.match(a.text,/取得できませんでした/);assert.equal(a.links.length,1);});
test('search URL encoding preserves arbitrary input without injection',()=>{const q='a&b=#<script>"';for(const link of webLinks(q))assert.equal(new URL(link.url).searchParams.get('q'),q);});
test('external turns count toward quota and do not invent profile facts',()=>{const data=JSON.parse(fs.readFileSync(new URL('../docs/profile.json',import.meta.url)));const c=new Conversation(data);c.respond('名前は？');c.recordExternal('天気',{text:'test'});assert.equal(c.history.length,2);assert.deepEqual(c.lastFactIds,[]);assert.deepEqual(c.history[1].factIds,[]);assert.match(c.respond('このチャットの会話は外部に送信する？').text,/ただし検索時/);});

test('exact Japanese city match removes fuzzy mountain candidates',async()=>{const p=await findPlaces('東京',{fetcher:async()=>({ok:true,json:async()=>({results:[{...place,name:'東京都',country_code:'JP'},{...place,name:'東境山',country_code:'JP'}]})})});assert.equal(p.length,1);assert.equal(p[0].name,'東京都');assert.equal(p[0].geocoding,true);assert.match(formatWeather(fixture,p[0],0).text,/GeoNames/);});

test('region reply keeps the requested forecast day and date words inside place names stay intact',async()=>{const c=new SearchController({findPlaces:async()=>[place],getWeather:async(_p,d)=>({text:String(d)})});await c.execute(c.plan('明日の天気'));const p=c.plan('東京');assert.equal(p.day,1);assert.equal((await c.execute(p)).text,'1');assert.equal(searchIntent('明日香の天気').place,'明日香');assert.equal(searchIntent('とうきょうの天気').day,0);});

test('hiragana polite requests and city names are not confused with personal words or filler',()=>{assert.equal(searchIntent('きょうのとうきょうのてんきおしえて').place,'とうきょう');assert.equal(searchIntent('かなざわのてんきは？').place,'かなざわ');assert.equal(searchIntent('weather at my location').useLocation,true);});
