import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {Conversation} from '../docs/dialogue.js';import {scoreQuestionExample} from '../docs/intent-retrieval.js';import {rankAnswerFacts,chooseWording} from '../docs/answer-priority.js';
const data=JSON.parse(fs.readFileSync(new URL('../docs/profile.json',import.meta.url)));
for(const question of ['名前は？','趣味は？','好きな人は？','サブスクは？','ランニングの靴は？','ランニングのアプリは？','記事では何について書いてる？'])test('wording variety with invariant facts and links: '+question,()=>{const c=new Conversation(data),answers=Array.from({length:8},()=>c.respond(question)),ids=[...answers[0].factIds].sort(),links=answers[0].links.map(l=>l.url).sort();assert.ok(new Set(answers.map(a=>a.text)).size>=4);for(const a of answers){assert.deepEqual([...a.factIds].sort(),ids);assert.deepEqual(a.links.map(l=>l.url).sort(),links);assert.doesNotMatch(a.text,/すみません/);}for(let i=1;i<answers.length;i++)assert.notEqual(answers[i].text,answers[i-1].text);});
test('answer priorities put the requested human contribution before tools',()=>{const a=new Conversation(data).respond('AIとの制作で自分の役割は？');assert.ok(a.text.indexOf('アイデア')<a.text.indexOf('ChatGPT'));});
test('answer weights preserve clause order and registered workflow order',()=>{const facts=data.facts.filter(f=>['name','tecirc-subjects'].includes(f.id));const a=[{factIds:['name'],intent:'identity-name'},{factIds:['tecirc-subjects'],intent:'article-subjects'}];assert.deepEqual(rankAnswerFacts(facts.reverse(),a).map(f=>f.id),['name','tecirc-subjects']);assert.match(new Conversation(data).respond('制作の流れは？').text,/プロンプト.*プレビュー.*改善/);});
test('question weighting distinguishes subjects from reading and limits semantic-only matching',()=>{const correct=scoreQuestionExample('記事のテーマを教えて','記事には何について書いてる？'),wrong=scoreQuestionExample('記事のテーマを教えて','記事を読むにはどうしたらいい');assert.ok(correct.score>wrong.score);assert.equal(wrong.conflict,.25);assert.ok(scoreQuestionExample('qxz記事zxq内容','記事のテーマは？').lexical<.2);});
test('wording choice searches past one repeated alternative',()=>{const f=i=>['a','b','c','d'][i%4];assert.equal(chooseWording(f,0,['a','b','c']),'d');});
test('unknown information and partial questions remain grounded',()=>{const c=new Conversation(data);for(let n=0;n<6;n++)assert.equal(c.respond('年齢は？').text,data.unknownReply);assert.match(c.respond('名前と年齢は？').text,/年齢については、まだ答えられません/);assert.equal(c.respond('通っている学校の名前は？').text,data.unknownReply);assert.equal(c.respond('Instagramのアカウントは？').text,data.unknownReply);assert.deepEqual(c.respond('Instagramについての記事ある？').factIds,['note-instants']);});
